### ISSUE TITLE
We got an error: Error: App Key and Secret Key must be defined

### ISSUE THREAD

**Issue by Tequirido** [Angelmaneuver/remember-the-milk.widget#1]
I tried using this Widget for the Übersicht App.

Once I copied the folder to the Übersicht Widget folder the widget loaded and showed the following error information:
We got an error: Error: App Key and Secret Key must be defined (See screenshot).

Is there anything that I am missing? It did not show me the setup as it does in your first screenshot.

![image](https://user-images.githubusercontent.com/121864666/210343309-f17f2834-f368-4c04-821d-82d0645fa556.png)

**Comment by Angelmaneuver** [comment]
Hi Tequirido.
I'll answer for your question.

## How to use this widget
To use this widget, you need an Remember The Milk's [account](https://www.rememberthemilk.com/) and an [API Key](https://www.rememberthemilk.com/services/api/).

You will need to obtain the API Key yourself.

## Reason
Originally, it would have been good if the API Key could have been incorporated into the widget, but this is because the API Key, which is confidential information, cannot be concealed due to the relationship provided on the JavaScript.

## Supplement
I've got a bit of Swift Know-how when I made another widget, so I'm going to modularise this widget around Remember The Milk using Swift.

If you don't want to use this widget in a hurry, you may be able to wait for that.

Well, the timing depends on my schedule and ability...


If there are no additional questions, I'll close this issue in about week.

**Comment by Tequirido** [comment]
Hello Angelmaneuver,
Thank you for the quick answer.

I do have the API key now through Remember the milk's website. Just not sure to which file I should add the API key to now.
Apologies for the, probably, very stupid questions, but not too familiar with Javascript. 

In your explanation you mentioned the following:
Set the API Key obtained from Remember the Milk to a variable in JavaScript of this widget. Then follow the on-screen instructions to grant access to your account.

Would you be able to explain in which file and how the variable should look like?

Thanks a lot again for your help!

**Comment by Angelmaneuver** [comment]
## Destination file for editing
Folder created by extracting the `task-deadline.widget.zip`.

`task-deadline.widget/index.jsx` is the file to be edited.

## Variables to be edited
| Setting value name | Variable            | index.jsx's line |
| :------------------  | :-------------  |  -------------:  |
| API Key                    | API_KEY           | 5                        |
| API Secret               | API_SECRET    | 6                        |

When you have finished editing, go to Übersicht and `Refresh All Widgets`.
