### ISSUE TITLE
Set-up error

### ISSUE THREAD

**Issue by ugandan-key** [Angelmaneuver/remember-the-milk.widget#2]
Hi there, I'm trying to use this widget and keep getting the following error:
We got an error: Error: bash: line 1: ./task-deadline.widget/bin/rtm-cli: Bad CPU type in executable
Don't know if it has anything to do with it, but my Mac uses Intel. Thank you for your work!
<img width="572" alt="image" src="https://user-images.githubusercontent.com/126182858/230206454-c2ea3180-bbb7-4e82-b250-ff952953d2da.png">

**Comment by Angelmaneuver** [comment]
Hi ugandan-key.
I'll answer for your issue.

It is assumed that this occurs because the module causing the problem (rtm-cli) is built with apple silicon.

If you fix it as follows, you can make it work with a JavaScript module instead of the module in problems, so try it.

However, you need to get the API Key and API Secret from Remember The Milk.

## Destination file for editing
Folder created by extracting the `task-deadline.widget.zip`.

`task-deadline.widget/index.jsx` is the file to be edited.

 \- `import * as RTM       from './lib/swift/rtm';`
 \+ `import * as RTM       from './lib/js/rtm';`

Thanks for reporting the issue.
If there are no additional questions, I'll close this issue in about week.

**Comment by ugandan-key** [comment]
Works like a charm, thanks a bunch!
